travis: Check for fatlabel test errors only for non-static builds
Static builds have broken iconv support which is detected at configure time
as usable. This leads to usage of internal CP850 conversion table as
fallback solution which throws runtime non-fatal error.

diff --git a/tests/test-label b/tests/test-label
--- a/tests/test-label
+++ b/tests/test-label
@@ -44,7 +44,7 @@ echo "Test $testname"
 rm -f "${testname}.img" "${testname}.out"
 
 xxd -r "${srcdir}/${testname}.xxd" "${testname}.img" || exit 99
-run_label "${testname}.img" 1> "${testname}.out" 2>&1 || exit 99
+run_label "${testname}.img" 1> "${testname}.out" 2> "${testname}.err" || exit 99
 
 
 echo "Comparing..."
@@ -52,5 +52,12 @@ diff "${testname}.out" "${srcdir}/${testname}.label"
 success=$?
 
 
-rm -f "${testname}.img" "${testname}.out"
+echo "Error output:"
+cat "${testname}.err"
+if [ "$CHECK_ERRORS" = "1" ] && [ -s "${testname}.err" ]; then
+	success=2
+fi
+
+
+rm -f "${testname}.img" "${testname}.out" "${testname}.err"
 exit $success
